### ISSUE TITLE
数据更新问题

### ISSUE THREAD

**Issue by telltime** [xluohome/phonedata#16]
非常感谢，很好用。但是好久没更新了，是弃坑了吗

**Comment by xluohome** [comment]
在更新的。

发自我的 iPhone

**Comment by WangSSSSS** [comment]
麻烦问下，更新的话，Mobile.csv数据会更新吗？因为我看上一次更新好像是18年4月份

**Comment by xluohome** [comment]
@WangSSSSS 会的，会同时提供csv

**Comment by xluohome** [comment]
@telltime @WangSSSSS 已做更新。  csv 数据库也已经上传；
