### ISSUE TITLE
1470485号段查询出来是广州，准确应该是深圳

### ISSUE THREAD

**Issue by coolhihi** [xluohome/phonedata#21]
1470485号段查询出来是广州，准确应该是深圳

**Comment by xluohome** [comment]
谢谢反馈。

发自我的 iPhone

**Comment by coolhihi** [comment]
1475841号段查询出来是广州，准确应该是清远
这边什么时候方便生成一个新的dat？147开头的号段查询错误率好高，有点糟

**Comment by xluohome** [comment]
已经修复， 请下载dat
