### ISSUE TITLE
虚拟运营商 phone_type信息错误

### ISSUE THREAD

**Issue by two4mamba** [xluohome/phonedata#28]
如1708144，是联通虚拟号码，最新的dat文件中phone_type却是移动虚拟运营商.

**Comment by xluohome** [comment]
谢谢，你的反馈。  
------------------
PHPOSS Team! 


 




------------------ 原始邮件 ------------------
发件人: "two4mamba"<notifications@github.com>; 
发送时间: 2019年9月29日(星期天) 中午11:22
收件人: "xluohome/phonedata"<phonedata@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [xluohome/phonedata] 虚拟运营商 phone_type信息错误 (#28)




如1708144，是联通虚拟号码，最新的dat文件中phone_type却是移动虚拟运营商.
 
&mdash;
