### ISSUE TITLE
这个dat文件怎么转成txt的呢？

### ISSUE THREAD

**Issue by Inblac** [xluohome/phonedata#3]
请问这个怎么转txt呢？

**Comment by xluohome** [comment]
你好， 源数据就是从txt装换成 dat数据库的。 不知道为何需要txt 呢？

**Comment by Inblac** [comment]
我想把数据导入数据库，作为一张表，在数据库里操作查询。
目前我用了比较笨的办法，用python接口遍历查询了一遍，把查询结果存成文本了。

**Comment by xluohome** [comment]
@Inblac  你是考虑效率 还是 ?   其实 无论通过二分法 还是 map内存 的方式,  都比较数据库查询要快的. 
目前我的4200u低电压cpu上  并发都可以进入到 700ns 一次的查询,
