### ISSUE TITLE
167号段无数据

### ISSUE THREAD

**Issue by Loveforkeeps** [xluohome/phonedata#32]
联通167号段无数据

demo:
16728574707
16779348766
16779348796

**Comment by sndnvaps** [comment]
可能还没有更新到数据库里面去。。

**Comment by xluohome** [comment]
PhoneNum: 16779348796
AreaZone: 0934
CardType: 中国联通虚拟运营商
City: 庆阳
ZipCode: 745000
Province: 甘肃
