### ISSUE TITLE
166、167、195等号码段无数据

### ISSUE THREAD

**Issue by lhs286266503** [xluohome/phonedata#33]
16690991091 河南濮阳号码（来源百度）
16699843893 新疆喀什
16687674077  云南德宏
16750318466 安徽 阜阳 中国联通 
19522432985 陕西 西安 中国移动
等

**Comment by xluohome** [comment]
感谢反馈。

**Comment by renjiawei0401** [comment]
@xluohome 什么时候更新号码库

**Comment by xluohome** [comment]
PhoneNum: 16690991091
AreaZone: 0393
CardType: 中国联通
City: 濮阳
ZipCode: 457000
Province: 河南
