### ISSUE TITLE
cmd/phonedata error

### ISSUE THREAD

**Issue by xishian** [xluohome/phonedata#35]
open C:/Users/xluo/Documents/goproject/src/github.com/xluohome/phonedata/phone.dat: no such file or directory

**Comment by xluohome** [comment]
请参考README.md

快速使用
cmd 目录下phonedata是一个命令行查询手机号归属地信息的终端程序。


Linux:
#PHONE_DATA_DIR=../ ./phonedata  18957509123

Windows:
>set PHONE_DATA_DIR=../
>phonedata.exe  18957509123

**Comment by xishian** [comment]
Thx
