### ISSUE TITLE
phone.dat怎么导入进mysql，dat格式的数据不知道怎么编辑啊？

### ISSUE THREAD

**Issue by zouhuigang** [xluohome/phonedata#4]
phone.dat怎么导入进mysql，dat格式的数据不知道怎么编辑啊？

**Comment by xluohome** [comment]
您好,
 phone.dat 是已被排序好的二进制文件, 方便通过二分法的算法进行高效数据查找,  相比数据库,dat文件更加容易部署使用,   而且目前已支持多个语言客户端库的程序实现.   phone.dat 数据库我这边也会定期进行更新.

**Comment by zouhuigang** [comment]
谢谢。明白了，会更新我就放心啦~~

**Comment by zouhuigang** [comment]
phone.dat这个文件是怎么生成的呢，求大神指导。
