### ISSUE TITLE
请教一个问题，为什么我从txt文本转化为dat格式的数据，生成的dat很大呢。解析是没问题的。就是很大。

### ISSUE THREAD

**Issue by zouhuigang** [xluohome/phonedata#5]

**Comment by xluohome** [comment]
记录有多少条 ？

**Comment by zouhuigang** [comment]
就是从你这里的库解析出来的txt，代码在https://github.com/zouhuigang/txt2dat,您给帮着看看~~

**Comment by zouhuigang** [comment]
就是从你这里的库解析出来的txt，代码在[https://github.com/zouhuigang/txt2dat](https://github.com/zouhuigang/txt2dat),您给帮着看看~~

**Comment by xluohome** [comment]
恩，你的转换程序 没有对  索引区 中的 “省市邮编区号“（江苏|常州|213000|0519）  去重。

**Comment by zouhuigang** [comment]
嗯嗯，一语点醒，现在已经解决了，生成phone.dat大小3128kb，太谢谢了。
