### ISSUE TITLE
运营商信息全部为0

### ISSUE THREAD

**Issue by quxf2012** [xluohome/phonedata#8]
你好,经过测试发现所有拿出来的<卡类型>数据都是0,不知是不是我方法有问题.
4月份的数据是utf-8编码的,7月的为GBK编码,

**Comment by xluohome** [comment]
感谢您的反馈，  一个小失误导致的，  已经 重新 强制更新了 git 版本修补了这个问题，  请 重新下载做测试；

**Comment by quxf2012** [comment]
多谢.
